mods.extendedcrafting.TableCrafting.addShaped("InfinityCatalyst", <item:avaritia:infinity_catalyst>, 
[
[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
[<item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>], 
[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:botania:life_essence>, <item:avaritia:crystal_matrix_ingot>, <item:botania:life_essence>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
[<item:minecraft:air>, <item:minecraft:air>, <item:botania:life_essence>, <item:avaritia:neutronium_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutronium_ingot>, <item:botania:life_essence>, <item:minecraft:air>, <item:minecraft:air>], 
[<item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>], 
[<item:minecraft:air>, <item:minecraft:air>, <item:botania:life_essence>, <item:avaritia:neutronium_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutronium_ingot>, <item:botania:life_essence>, <item:minecraft:air>, <item:minecraft:air>], 
[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:botania:life_essence>, <item:avaritia:crystal_matrix_ingot>, <item:botania:life_essence>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
[<item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>], 
[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]
);  