mods.extendedcrafting.TableCrafting.addShaped("tomeofknowledge", <item:projecte:tome>, 
[
[<item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>], 
[<item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:mekanism:crystal_osmium>, <item:mekanism:crystal_osmium>, <item:mekanism:crystal_osmium>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
[<item:projectex:fading_matter>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999" as string}]}}), <item:mekanism:creative_fluid_tank>, <item:mekanism:creative_chemical_tank>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:projectex:fading_matter>], 
[<item:projectex:fading_matter>, <item:mekanism:crystal_gold>, <item:bloodmagic:activationcrystalcreative>, <item:avaritia:infinity_catalyst>, <item:astralsorcery:shifting_star_vicio>, <item:avaritia:infinity_catalyst>, <item:create:creative_blaze_cake>, <item:mekanism:crystal_lead>, <item:projectex:fading_matter>], 
[<item:projectex:fading_matter>, <item:mekanism:crystal_gold>, <item:botania:creative_pool>, <item:mahoutsukai:mana_circuit_magitech>, <item:projecte:transmutation_tablet>, <item:mahoutsukai:mana_circuit_magitech>, <item:createaddition:creative_energy>, <item:mekanism:crystal_lead>, <item:projectex:fading_matter>], 
[<item:projectex:fading_matter>, <item:mekanism:crystal_gold>, <item:appliedenergistics2:creative_energy_cell>, <item:avaritia:infinity_catalyst>, <item:astralsorcery:shifting_star_aevitas>, <item:avaritia:infinity_catalyst>, <item:create:creative_motor>, <item:mekanism:crystal_lead>, <item:projectex:fading_matter>], 
[<item:projectex:fading_matter>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:refinedstorage:creative_fluid_storage_disk>, <item:refinedstorage:creative_storage_disk>, <item:refinedstorage:creative_controller>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:projectex:fading_matter>], 
[<item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:mekanism:crystal_uranium>, <item:mekanism:crystal_uranium>, <item:mekanism:crystal_uranium>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
[<item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>]
]
);  
