craftingTable.removeByName("projecte:philosophers_stone");
craftingTable.removeByName("projecte:philosophers_stone_alt");
mods.extendedcrafting.TableCrafting.addShaped("philo", <item:projecte:philosophers_stone>, 
[
[<item:botania:life_essence>, <item:botania:life_essence>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:botania:life_essence>, <item:botania:life_essence>], 
[<item:botania:life_essence>, <item:projecte:red_matter>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:astralsorcery:resonating_gem>, <item:projecte:red_matter>, <item:botania:life_essence>], 
[<item:extendedcrafting:redstone_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:redstone_ingot>], 
[<item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:redstone_ingot>], 
[<item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:endest_pearl>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:redstone_ingot>], 
[<item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:redstone_ingot>], 
[<item:extendedcrafting:redstone_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:redstone_ingot>], 
[<item:minecraft:air>, <item:projecte:red_matter>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:astralsorcery:resonating_gem>, <item:projecte:red_matter>, <item:minecraft:air>],
[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]
); 